/* The following code was generated by JFlex 1.6.1 */

package lexer;
import static lexer.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>./src/lexer/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MYSTRING = 2;
  public static final int MYCHAR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\65\1\57\1\12\1\13\1\13\1\11\22\65\1\10\1\50\1\15"+
    "\1\14\1\65\1\46\1\53\1\63\1\6\1\6\1\44\1\43\1\6"+
    "\1\43\1\56\1\45\1\3\1\4\6\5\2\2\1\6\1\65\1\51"+
    "\1\47\1\52\2\65\1\1\1\60\14\1\1\61\10\1\1\62\2\1"+
    "\1\54\1\66\1\55\1\53\1\1\1\65\1\16\1\23\1\25\1\33"+
    "\1\20\1\7\1\40\1\42\1\31\1\1\1\24\1\26\1\37\1\30"+
    "\1\27\1\35\1\1\1\21\1\17\1\22\1\32\1\1\1\41\1\34"+
    "\1\36\1\1\1\65\1\53\1\65\1\53\1\65\5\64\1\67\32\64"+
    "\1\0\u15df\64\1\0\u097f\64\13\0\35\64\1\67\1\67\5\64\1\0"+
    "\57\64\1\0\u0fa0\64\1\0\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\uffff\64\ud00f\64";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\2\3\1\4\1\2\3\5\1\6"+
    "\17\2\4\7\1\10\1\1\2\11\1\12\1\1\1\13"+
    "\1\14\2\15\1\16\1\14\1\17\1\20\1\21\1\0"+
    "\3\21\4\2\1\0\16\2\1\22\1\2\2\23\6\2"+
    "\1\10\1\11\1\24\1\25\1\26\1\27\1\30\3\3"+
    "\3\2\1\0\23\2\1\0\11\2\1\0\4\2\1\5"+
    "\1\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\250"+
    "\0\u0188\0\250\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\250"+
    "\0\u0658\0\u0658\0\u0690\0\u06c8\0\250\0\u0700\0\250\0\250"+
    "\0\u0738\0\250\0\250\0\u0770\0\250\0\u07a8\0\u07e0\0\u0818"+
    "\0\u0850\0\u0888\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8"+
    "\0\u0a10\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98"+
    "\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\340\0\u0d20"+
    "\0\340\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8"+
    "\0\250\0\250\0\250\0\250\0\250\0\250\0\u0818\0\u0850"+
    "\0\u0888\0\u08c0\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8"+
    "\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8"+
    "\0\u11f0\0\u1228\0\u0d58\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340"+
    "\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500"+
    "\0\u1538\0\u1570\0\u15a8\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0"+
    "\0\u15e0\0\u16f8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\2\6\1\10\1\11\1\12"+
    "\1\13\1\12\1\0\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\5\1\24\1\25\1\26\1\27"+
    "\1\30\1\5\1\31\1\5\1\32\2\5\1\33\1\34"+
    "\1\5\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\4\2\10\3\5\1\47\3\4"+
    "\1\0\1\4\7\50\1\4\1\51\1\52\1\0\1\50"+
    "\1\53\41\50\1\4\6\50\1\54\1\0\1\4\7\50"+
    "\1\4\3\0\43\50\1\4\3\50\1\55\3\50\71\0"+
    "\1\56\5\5\1\0\1\5\6\0\25\5\15\0\3\5"+
    "\1\0\1\56\2\0\1\56\1\0\1\57\4\6\1\0"+
    "\1\57\6\0\25\57\13\0\1\60\1\0\3\57\6\0"+
    "\1\57\4\6\1\0\1\57\6\0\5\57\1\61\3\57"+
    "\1\62\4\57\1\63\6\57\13\0\1\60\1\0\1\61"+
    "\1\62\1\63\5\0\1\56\5\5\1\0\1\5\6\0"+
    "\3\5\1\64\4\5\1\65\1\66\1\5\1\67\11\5"+
    "\15\0\3\5\1\0\1\56\2\0\1\56\12\0\1\12"+
    "\55\0\11\14\1\13\1\12\55\14\15\0\1\70\52\0"+
    "\1\56\5\5\1\0\1\5\6\0\1\5\1\71\10\5"+
    "\1\72\12\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\4\5\1\73\20\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\10\5\1\74\5\5\1\75\6\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\1\76\1\5\1\77\22\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\3\5\1\100"+
    "\21\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\5\6\0\3\5\1\101\5\5\1\102\13\5"+
    "\15\0\3\5\1\0\1\56\2\0\2\56\5\5\1\0"+
    "\1\5\6\0\10\5\1\103\1\104\13\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\1\105\12\5\1\106\11\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\3\5\1\107"+
    "\21\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\5\6\0\11\5\1\110\13\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\111\6\0"+
    "\1\5\1\111\10\5\1\112\6\5\1\113\3\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\2\5\1\114\22\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\1\115\2\5"+
    "\1\116\21\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\10\5\1\117\14\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\24\5\1\120\15\0\3\5\1\0\1\56\2\0"+
    "\1\56\47\0\1\121\64\0\1\35\2\0\1\121\65\0"+
    "\1\35\1\0\1\121\67\0\1\122\67\0\1\122\1\0"+
    "\1\45\1\122\64\0\1\122\2\0\1\45\72\0\1\10"+
    "\24\0\1\52\72\0\1\123\3\0\1\124\1\125\5\0"+
    "\1\126\37\0\6\56\1\0\1\56\6\0\25\56\15\0"+
    "\3\56\1\0\1\56\2\0\1\56\1\0\5\57\1\0"+
    "\1\57\6\0\25\57\15\0\3\57\7\0\4\127\63\0"+
    "\2\57\2\130\1\57\1\0\1\57\6\0\25\57\15\0"+
    "\3\57\6\0\2\57\3\131\1\0\1\57\6\0\25\57"+
    "\15\0\3\57\6\0\1\57\4\132\1\0\1\132\6\0"+
    "\1\132\1\57\1\132\2\57\1\132\1\57\1\132\5\57"+
    "\1\132\7\57\15\0\3\57\5\0\1\56\5\5\1\0"+
    "\1\5\6\0\11\5\1\133\13\5\15\0\3\5\1\0"+
    "\1\56\2\0\2\56\5\5\1\0\1\5\6\0\11\5"+
    "\1\134\13\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\3\5\1\111\21\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\12\5\1\135\12\5\15\0\3\5\1\0\1\56"+
    "\2\0\1\56\15\0\1\136\52\0\1\56\5\5\1\0"+
    "\1\5\6\0\1\5\1\137\23\5\15\0\3\5\1\0"+
    "\1\56\2\0\2\56\5\5\1\0\1\5\6\0\15\5"+
    "\1\107\7\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\3\5\1\140\21\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\1\5\1\141\11\5\1\142\11\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\2\5\1\143\4\5\1\144\15\5\15\0\3\5\1\0"+
    "\1\56\2\0\2\56\5\5\1\0\1\5\6\0\13\5"+
    "\1\145\11\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\4\5\1\146\20\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\20\5\1\111\4\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\2\5\1\147"+
    "\22\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\5\6\0\11\5\1\150\13\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\1\115\24\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\12\5\1\151\12\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\21\5\1\152\3\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\1\5\1\153"+
    "\23\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\5\6\0\4\5\1\107\20\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\4\5\1\111\20\5\15\0\3\5\1\0\1\56\2\0"+
    "\2\56\5\5\1\0\1\5\6\0\17\5\1\154\5\5"+
    "\15\0\3\5\1\0\1\56\2\0\2\56\5\5\1\0"+
    "\1\111\6\0\10\5\1\111\14\5\15\0\3\5\1\0"+
    "\1\56\2\0\2\56\5\5\1\0\1\5\6\0\1\5"+
    "\1\155\23\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\13\5\1\156\11\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\11\5\1\157\13\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\13\5\1\160"+
    "\11\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\5\6\0\21\5\1\111\3\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\1\153\24\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\1\161\24\5\15\0\3\5"+
    "\1\0\1\56\2\0\1\56\15\136\1\162\52\136\1\56"+
    "\5\5\1\0\1\5\6\0\2\5\1\163\22\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\13\5\1\164\11\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\2\5\1\111"+
    "\22\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\111\6\0\25\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\7\5\1\111"+
    "\15\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\5\6\0\2\5\1\165\22\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\1\5\1\141\23\5\15\0\3\5\1\0\1\56\2\0"+
    "\2\56\5\5\1\0\1\5\6\0\14\5\1\166\10\5"+
    "\15\0\3\5\1\0\1\56\2\0\2\56\5\5\1\0"+
    "\1\5\6\0\1\167\24\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\10\5\1\111"+
    "\14\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\5\6\0\4\5\1\170\20\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\5\5\1\171\17\5\15\0\3\5\1\0\1\56\2\0"+
    "\2\56\5\5\1\0\1\5\6\0\11\5\1\163\13\5"+
    "\15\0\3\5\1\0\1\56\2\0\2\56\5\5\1\0"+
    "\1\5\6\0\1\5\1\111\23\5\15\0\3\5\1\0"+
    "\1\56\2\0\2\56\5\5\1\0\1\5\6\0\12\5"+
    "\1\153\12\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\5\5\1\172\17\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\10\5\1\141\14\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\10\5\1\173"+
    "\14\5\15\0\3\5\1\0\1\56\2\0\1\56\15\136"+
    "\1\174\52\136\1\56\5\5\1\0\1\5\6\0\3\5"+
    "\1\153\21\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\12\5\1\175\12\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\17\5\1\153\5\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\3\5\1\176"+
    "\21\5\15\0\3\5\1\0\1\56\2\0\2\56\5\5"+
    "\1\0\1\5\6\0\6\5\1\111\16\5\15\0\3\5"+
    "\1\0\1\56\2\0\2\56\5\5\1\0\1\5\6\0"+
    "\13\5\1\177\11\5\15\0\3\5\1\0\1\56\2\0"+
    "\2\56\5\5\1\0\1\5\6\0\15\5\1\200\7\5"+
    "\15\0\3\5\1\0\1\56\2\0\2\56\5\5\1\0"+
    "\1\5\6\0\1\150\24\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\10\5\1\100"+
    "\14\5\15\0\3\5\1\0\1\56\2\0\1\56\15\136"+
    "\1\201\52\136\1\56\5\5\1\0\1\5\6\0\22\5"+
    "\1\111\2\5\15\0\3\5\1\0\1\56\2\0\2\56"+
    "\5\5\1\0\1\5\6\0\12\5\1\111\12\5\15\0"+
    "\3\5\1\0\1\56\2\0\2\56\5\5\1\0\1\5"+
    "\6\0\12\5\1\202\12\5\15\0\3\5\1\0\1\56"+
    "\2\0\2\56\5\5\1\0\1\5\6\0\1\111\24\5"+
    "\15\0\3\5\1\0\1\56\2\0\2\56\5\5\1\0"+
    "\1\5\6\0\14\5\1\141\10\5\15\0\3\5\1\0"+
    "\1\56\2\0\1\56";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5936];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\3\1\1\11\1\1\1\11\25\1\1\11"+
    "\4\1\1\11\1\1\2\11\1\1\2\11\1\1\1\11"+
    "\2\1\1\0\7\1\1\0\30\1\6\11\7\1\1\0"+
    "\23\1\1\0\11\1\1\0\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //esto se copia directamente

    StringBuffer string = new StringBuffer();
    Boolean cambioLinea = false;

    public String lexeme;
    public int getLine(){
        return yyline;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 222) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case MYSTRING: {
              yybegin(YYINITIAL); lexeme = "String sin terminar: " + string.toString(); return ERROR;
            }
            case 131: break;
            case MYCHAR: {
              yybegin(YYINITIAL); lexeme = "Char sin terminar: " + string.toString(); return ERROR;
            }
            case 132: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = yytext();return ERROR;
            }
          case 25: break;
          case 2: 
            { lexeme=yytext(); return Identificador;
            }
          case 26: break;
          case 3: 
            { lexeme=yytext(); return INT;
            }
          case 27: break;
          case 4: 
            { lexeme = yytext(); return opDelimitadores;
            }
          case 28: break;
          case 5: 
            { /* ignore */
            }
          case 29: break;
          case 6: 
            { string.setLength(0); cambioLinea = false; yybegin(MYSTRING);
            }
          case 30: break;
          case 7: 
            { lexeme = yytext(); return opAritmeticos;
            }
          case 31: break;
          case 8: 
            { lexeme = yytext(); return opAsignaciones;
            }
          case 32: break;
          case 9: 
            { lexeme = yytext(); return opComparadores ;
            }
          case 33: break;
          case 10: 
            { lexeme = yytext(); return opBits;
            }
          case 34: break;
          case 11: 
            { string.setLength(0); yybegin(MYCHAR);
            }
          case 35: break;
          case 12: 
            { string.append( yytext() );
            }
          case 36: break;
          case 13: 
            { cambioLinea = true;
            }
          case 37: break;
          case 14: 
            { yybegin(YYINITIAL);
                                   lexeme = "\"" +string.toString()+"\"";
                                   if(cambioLinea){
                                        return ERROR;
                                   }else{
                                        return STRING;
                                   }
            }
          case 38: break;
          case 15: 
            { yybegin(YYINITIAL); lexeme = "'"+ string.toString()+"'"; 
                                 if(string.length()>1)
                                    return ERROR;
                                 else
                                    return CHAR;
            }
          case 39: break;
          case 16: 
            { lexeme="string"+yytext(); return ERROR;
            }
          case 40: break;
          case 17: 
            { lexeme = yytext(); return ERROR;
            }
          case 41: break;
          case 18: 
            { lexeme = yytext(); return opLogicos;
            }
          case 42: break;
          case 19: 
            { lexeme = yytext(); return PalabraReservada;
            }
          case 43: break;
          case 20: 
            { string.append('\"');
            }
          case 44: break;
          case 21: 
            { string.append('\r');
            }
          case 45: break;
          case 22: 
            { string.append('\t');
            }
          case 46: break;
          case 23: 
            { string.append('\n');
            }
          case 47: break;
          case 24: 
            { lexeme=yytext(); return FLOAT;
            }
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
