/* The following code was generated by JFlex 1.6.1 */

package lexer;
import static lexer.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>./src/lexer/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MYSTRING = 2;
  public static final int MYCHAR = 4;
  public static final int COMENTARIOBLOQUE = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\63\1\55\1\12\1\13\1\13\1\11\22\63\1\10\1\50\1\15"+
    "\1\14\1\63\1\46\1\53\1\61\1\6\1\6\1\44\1\43\1\6"+
    "\1\43\1\54\1\45\1\3\1\4\6\5\2\2\1\6\1\63\1\51"+
    "\1\47\1\52\2\63\1\1\1\56\14\1\1\57\10\1\1\60\2\1"+
    "\1\6\1\64\1\6\1\53\1\1\1\63\1\16\1\23\1\25\1\33"+
    "\1\20\1\7\1\40\1\42\1\31\1\1\1\24\1\26\1\37\1\30"+
    "\1\27\1\35\1\1\1\21\1\17\1\22\1\32\1\1\1\41\1\34"+
    "\1\36\1\1\1\6\1\53\1\6\1\53\1\63\5\62\1\65\32\62"+
    "\1\0\u15df\62\1\0\u097f\62\13\0\35\62\1\65\1\65\5\62\1\0"+
    "\57\62\1\0\u0fa0\62\1\0\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\uffff\62\ud00f\62";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\2\3\1\4\1\2\3\5\1\6"+
    "\17\2\4\7\1\10\1\1\2\11\1\12\1\13\1\14"+
    "\1\15\2\16\1\17\1\20\1\14\1\21\2\22\1\14"+
    "\1\23\1\24\1\0\3\24\4\2\1\0\16\2\1\25"+
    "\1\2\2\26\6\2\1\10\1\11\1\27\1\30\1\31"+
    "\1\0\1\32\3\3\3\2\1\33\22\2\1\34\17\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\330\0\u01b0\0\330\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be"+
    "\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e"+
    "\0\u04a4\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e"+
    "\0\330\0\u0654\0\u0654\0\u068a\0\u06c0\0\330\0\330\0\330"+
    "\0\330\0\u06f6\0\330\0\330\0\330\0\u072c\0\330\0\330"+
    "\0\u0762\0\u0798\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc"+
    "\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c"+
    "\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c"+
    "\0\u0c72\0\u0ca8\0\u0cde\0\u010e\0\u0d14\0\u010e\0\u0d4a\0\u0d80"+
    "\0\u0db6\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\330\0\330\0\330"+
    "\0\330\0\330\0\u0ec4\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0efa"+
    "\0\u0f30\0\u0f66\0\330\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074"+
    "\0\u10aa\0\u10e0\0\u1116\0\u114c\0\u1182\0\u11b8\0\u11ee\0\u0d4a"+
    "\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc\0\330\0\u1332\0\u1368"+
    "\0\u139e\0\u13d4\0\u140a\0\u1440\0\u1476\0\u14ac\0\u14e2\0\u1518"+
    "\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\2\7\1\11\1\12\1\13"+
    "\1\14\1\13\1\0\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\6\1\25\1\26\1\27\1\30"+
    "\1\31\1\6\1\32\1\6\1\33\2\6\1\34\1\35"+
    "\1\6\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\2\11\3\6\1\47\3\5\1\0\1\5"+
    "\7\50\1\51\1\52\1\53\1\0\1\50\1\54\37\50"+
    "\1\55\6\50\1\56\1\0\61\50\1\57\4\50\1\60"+
    "\7\50\1\51\1\61\2\60\1\50\1\62\37\50\1\60"+
    "\6\50\1\56\1\60\66\0\1\63\5\6\1\0\1\6"+
    "\6\0\25\6\13\0\3\6\1\0\1\63\2\0\1\63"+
    "\1\0\1\64\4\7\1\0\1\64\6\0\25\64\11\0"+
    "\1\65\1\0\3\64\6\0\1\64\4\7\1\0\1\64"+
    "\6\0\5\64\1\66\3\64\1\67\4\64\1\70\6\64"+
    "\11\0\1\65\1\0\1\66\1\67\1\70\5\0\1\63"+
    "\5\6\1\0\1\6\6\0\3\6\1\71\4\6\1\72"+
    "\1\73\1\6\1\74\11\6\13\0\3\6\1\0\1\63"+
    "\2\0\1\63\12\0\1\13\53\0\11\15\1\14\1\13"+
    "\53\15\15\0\1\75\50\0\1\63\5\6\1\0\1\6"+
    "\6\0\1\6\1\76\10\6\1\77\12\6\13\0\3\6"+
    "\1\0\1\63\2\0\2\63\5\6\1\0\1\6\6\0"+
    "\4\6\1\100\20\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\10\6\1\101\5\6"+
    "\1\102\6\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\1\103\1\6\1\104\22\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\3\6\1\105\21\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\3\6"+
    "\1\106\5\6\1\107\13\6\13\0\3\6\1\0\1\63"+
    "\2\0\2\63\5\6\1\0\1\6\6\0\10\6\1\110"+
    "\1\111\13\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\1\112\12\6\1\113\11\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\3\6\1\114\21\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\11\6"+
    "\1\115\13\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\116\6\0\1\6\1\116\10\6\1\117"+
    "\6\6\1\120\3\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\2\6\1\121\22\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\1\122\2\6\1\123\21\6\13\0\3\6"+
    "\1\0\1\63\2\0\2\63\5\6\1\0\1\6\6\0"+
    "\10\6\1\124\14\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\24\6\1\125\13\0"+
    "\3\6\1\0\1\63\2\0\1\63\47\0\1\126\62\0"+
    "\1\36\2\0\1\126\63\0\1\36\1\0\1\126\65\0"+
    "\1\127\65\0\1\127\1\0\1\46\1\127\62\0\1\127"+
    "\2\0\1\46\25\0\1\53\70\0\1\130\3\0\1\131"+
    "\1\55\5\0\1\132\47\0\1\60\70\0\1\133\50\0"+
    "\6\63\1\0\1\63\6\0\25\63\13\0\3\63\1\0"+
    "\1\63\2\0\1\63\1\0\5\64\1\0\1\64\6\0"+
    "\25\64\13\0\3\64\7\0\4\134\61\0\2\64\2\135"+
    "\1\64\1\0\1\64\6\0\25\64\13\0\3\64\6\0"+
    "\2\64\3\136\1\0\1\64\6\0\25\64\13\0\3\64"+
    "\6\0\1\64\4\137\1\0\1\137\6\0\1\137\1\64"+
    "\1\137\2\64\1\137\1\64\1\137\5\64\1\137\7\64"+
    "\13\0\3\64\5\0\1\63\5\6\1\0\1\6\6\0"+
    "\11\6\1\140\13\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\11\6\1\141\13\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\3\6\1\116\21\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\12\6"+
    "\1\142\12\6\13\0\3\6\1\0\1\63\2\0\1\63"+
    "\15\0\1\143\50\0\1\63\5\6\1\0\1\6\6\0"+
    "\1\6\1\144\23\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\15\6\1\114\7\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\3\6\1\145\21\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\1\6"+
    "\1\146\11\6\1\147\11\6\13\0\3\6\1\0\1\63"+
    "\2\0\2\63\5\6\1\0\1\6\6\0\2\6\1\150"+
    "\4\6\1\151\15\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\13\6\1\152\11\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\4\6\1\153\20\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\20\6"+
    "\1\116\4\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\2\6\1\154\22\6\13\0"+
    "\3\6\1\0\1\63\2\0\2\63\5\6\1\0\1\6"+
    "\6\0\11\6\1\155\13\6\13\0\3\6\1\0\1\63"+
    "\2\0\2\63\5\6\1\0\1\6\6\0\1\122\24\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\12\6\1\156\12\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\21\6"+
    "\1\157\3\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\1\6\1\160\23\6\13\0"+
    "\3\6\1\0\1\63\2\0\2\63\5\6\1\0\1\6"+
    "\6\0\4\6\1\114\20\6\13\0\3\6\1\0\1\63"+
    "\2\0\2\63\5\6\1\0\1\6\6\0\4\6\1\116"+
    "\20\6\13\0\3\6\1\0\1\63\2\0\2\63\5\6"+
    "\1\0\1\6\6\0\17\6\1\161\5\6\13\0\3\6"+
    "\1\0\1\63\2\0\2\63\5\6\1\0\1\116\6\0"+
    "\10\6\1\116\14\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\1\6\1\162\23\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\13\6\1\163\11\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\11\6"+
    "\1\164\13\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\13\6\1\165\11\6\13\0"+
    "\3\6\1\0\1\63\2\0\1\63\15\0\1\166\50\0"+
    "\1\63\5\6\1\0\1\6\6\0\21\6\1\116\3\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\1\160\24\6\13\0\3\6\1\0\1\63"+
    "\2\0\2\63\5\6\1\0\1\6\6\0\1\167\24\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\2\6\1\170\22\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\13\6"+
    "\1\171\11\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\2\6\1\116\22\6\13\0"+
    "\3\6\1\0\1\63\2\0\2\63\5\6\1\0\1\116"+
    "\6\0\25\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\7\6\1\116\15\6\13\0"+
    "\3\6\1\0\1\63\2\0\2\63\5\6\1\0\1\6"+
    "\6\0\2\6\1\172\22\6\13\0\3\6\1\0\1\63"+
    "\2\0\2\63\5\6\1\0\1\6\6\0\1\6\1\146"+
    "\23\6\13\0\3\6\1\0\1\63\2\0\2\63\5\6"+
    "\1\0\1\6\6\0\14\6\1\173\10\6\13\0\3\6"+
    "\1\0\1\63\2\0\2\63\5\6\1\0\1\6\6\0"+
    "\1\174\24\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\10\6\1\116\14\6\13\0"+
    "\3\6\1\0\1\63\2\0\2\63\5\6\1\0\1\6"+
    "\6\0\4\6\1\175\20\6\13\0\3\6\1\0\1\63"+
    "\2\0\2\63\5\6\1\0\1\6\6\0\5\6\1\176"+
    "\17\6\13\0\3\6\1\0\1\63\2\0\2\63\5\6"+
    "\1\0\1\6\6\0\11\6\1\170\13\6\13\0\3\6"+
    "\1\0\1\63\2\0\2\63\5\6\1\0\1\6\6\0"+
    "\1\6\1\116\23\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\12\6\1\160\12\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\5\6\1\177\17\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\10\6"+
    "\1\146\14\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\10\6\1\200\14\6\13\0"+
    "\3\6\1\0\1\63\2\0\2\63\5\6\1\0\1\6"+
    "\6\0\3\6\1\160\21\6\13\0\3\6\1\0\1\63"+
    "\2\0\2\63\5\6\1\0\1\6\6\0\12\6\1\201"+
    "\12\6\13\0\3\6\1\0\1\63\2\0\2\63\5\6"+
    "\1\0\1\6\6\0\17\6\1\160\5\6\13\0\3\6"+
    "\1\0\1\63\2\0\2\63\5\6\1\0\1\6\6\0"+
    "\3\6\1\202\21\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\6\6\1\116\16\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\13\6\1\203\11\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\15\6"+
    "\1\204\7\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\1\155\24\6\13\0\3\6"+
    "\1\0\1\63\2\0\2\63\5\6\1\0\1\6\6\0"+
    "\10\6\1\105\14\6\13\0\3\6\1\0\1\63\2\0"+
    "\2\63\5\6\1\0\1\6\6\0\22\6\1\116\2\6"+
    "\13\0\3\6\1\0\1\63\2\0\2\63\5\6\1\0"+
    "\1\6\6\0\12\6\1\116\12\6\13\0\3\6\1\0"+
    "\1\63\2\0\2\63\5\6\1\0\1\6\6\0\12\6"+
    "\1\205\12\6\13\0\3\6\1\0\1\63\2\0\2\63"+
    "\5\6\1\0\1\6\6\0\1\116\24\6\13\0\3\6"+
    "\1\0\1\63\2\0\2\63\5\6\1\0\1\6\6\0"+
    "\14\6\1\146\10\6\13\0\3\6\1\0\1\63\2\0"+
    "\1\63";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5724];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\3\1\1\11\1\1\1\11\25\1\1\11"+
    "\4\1\4\11\1\1\3\11\1\1\2\11\4\1\1\0"+
    "\7\1\1\0\30\1\5\11\1\0\7\1\1\11\22\1"+
    "\1\11\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //esto se copia directamente

    StringBuffer string = new StringBuffer();
    Boolean cambioLinea = false;

    public String lexeme;
    public int getLine(){
        return yyline;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 222) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case MYSTRING: {
              yybegin(YYINITIAL); lexeme = "String sin terminar: " + string.toString(); return ERROR;
            }
            case 134: break;
            case MYCHAR: {
              yybegin(YYINITIAL); lexeme = "Char sin terminar: " + string.toString(); return ERROR;
            }
            case 135: break;
            case COMENTARIOBLOQUE: {
              yybegin(YYINITIAL); lexeme = "Comentario de bloque sin terminar: " + "\"\"\"" + string.toString(); return ERROR;
            }
            case 136: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme = yytext();return ERROR;
            }
          case 29: break;
          case 2: 
            { lexeme=yytext(); return Identificador;
            }
          case 30: break;
          case 3: 
            { lexeme=yytext(); return INT;
            }
          case 31: break;
          case 4: 
            { lexeme = yytext(); return opDelimitadores;
            }
          case 32: break;
          case 5: 
            { /* ignore */
            }
          case 33: break;
          case 6: 
            { string.setLength(0); cambioLinea = false; yybegin(MYSTRING);
            }
          case 34: break;
          case 7: 
            { lexeme = yytext(); return opAritmeticos;
            }
          case 35: break;
          case 8: 
            { lexeme = yytext(); return opAsignaciones;
            }
          case 36: break;
          case 9: 
            { lexeme = yytext(); return opComparadores ;
            }
          case 37: break;
          case 10: 
            { lexeme = yytext(); return opBits;
            }
          case 38: break;
          case 11: 
            { string.setLength(0); yybegin(MYCHAR);
            }
          case 39: break;
          case 12: 
            { string.append( yytext() );
            }
          case 40: break;
          case 13: 
            { string.append(' ');
            }
          case 41: break;
          case 14: 
            { cambioLinea = true; string.append('\n');
            }
          case 42: break;
          case 15: 
            { yybegin(YYINITIAL);
                                   lexeme = "\"" +string.toString()+"\"";
                                   if(cambioLinea){
                                        return ERROR;
                                   }else{
                                        return STRING;
                                   }
            }
          case 43: break;
          case 16: 
            { string.append('\t');
            }
          case 44: break;
          case 17: 
            { yybegin(YYINITIAL); lexeme = "'"+ string.toString()+"'"; 
                                 if(string.length()>1)
                                    return ERROR;
                                 else
                                    return CHAR;
            }
          case 45: break;
          case 18: 
            { string.append(yytext());
            }
          case 46: break;
          case 19: 
            { lexeme=yytext(); return ERROR;
            }
          case 47: break;
          case 20: 
            { lexeme = yytext(); return ERROR;
            }
          case 48: break;
          case 21: 
            { lexeme = yytext(); return opLogicos;
            }
          case 49: break;
          case 22: 
            { lexeme = yytext(); return PalabraReservada;
            }
          case 50: break;
          case 23: 
            { string.append('\"');
            }
          case 51: break;
          case 24: 
            { string.append('\r');
            }
          case 52: break;
          case 25: 
            { string.append('\n');
            }
          case 53: break;
          case 26: 
            { lexeme=yytext(); return FLOAT;
            }
          case 54: break;
          case 27: 
            { string.setLength(0); yybegin(COMENTARIOBLOQUE);
            }
          case 55: break;
          case 28: 
            { yybegin(YYINITIAL); System.out.println(string.toString());
            }
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
